baseURL = "https://codingpot.github.io/"
languageCode = "en-us"
title = "코딩냄비 부글부글"
theme = "cactus"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CI/CD"
url = "/cicd"
weight = 2

[[menu.main]]
name = "MLOps"
url = "/mlops"
weight = 3